const actionTypes = {
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  SIGNUPFAIL: 'SIGNUPFAIL',
  SIGNUPSUCCESS: 'SIGNUPSUCCESS',
  LOGINFAIL: 'LOGINFAIL',
  LOGINSUCCESS: 'LOGINSUCCESS',
  GET_TAGS: 'GET_TAGS',
  GET_MENU: 'GET_MENU'
};
export default actionTypes;
